from st_pages import Page, show_pages, hide_pages
import streamlit as st

class PageRender:
    def __init__(self):
        pass

    @staticmethod
    def showPages():
        """Shows all pages in sidebar."""
        show_pages(
        [
            Page("home.py", "Home", "🏠"),
            Page("pages/help.py", "How to Play", "❓"),
            Page("pages/map_screen.py", "Game Map", "🗺️"),
            Page("pages/main.py", "Main Gameplay", "🎮"),
            Page("pages/lose.py", "You Lost!", "💀"),
            Page("pages/win.py", "You Won!", "🏆"),
            Page("pages/trivia_screen.py", "Trivia", "📚"),
            Page("pages/shooting_game.py", "Shooting Minigame", "🎯"),
            Page("pages/leaderboard.py", "Leaderboard", "🥇"),
            Page("pages/stats.py", "Stats", "📈"),
            Page("pages/speechGame.py", "Accessibility Gameplay", "♿"),
        ]
    )
        
    
    @staticmethod
    def renderHidden():
        """Renders pages in the sidebar to be all hidden."""
        PageRender.showPages()
        hide_pages(
            [
                "Home",
                "Game Map",
                "How to Play",
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Shooting Minigame",
                "Leaderboard",
                "Stats",
                "Accessibility Gameplay",
            ]
        )

    @staticmethod
    def renderMain():
        """Renders the shown pages in the sidebar in main."""
        PageRender.showPages()
        hide_pages(
            [
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Shooting Minigame",
                "Leaderboard",
                "Stats",
                "Accessibility Gameplay",                
            ]
        )

    @staticmethod
    def renderMap():
        """Renders the shown pages in the sidebar in map."""
        PageRender.showPages()
        hide_pages(
            [
                "Home",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Shooting Minigame",
                "Leaderboard",
                "Stats",
                "Accessibility Gameplay",
            ]
        )

    @staticmethod
    def renderInstr():
        """Renders the shown pages in the sidebar for how to play."""
        PageRender.showPages()
        hide_pages(
            [
                "Home",
                "Game Map",
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Stats",
                "Shooting Minigame",
                "Leaderboard",
                "Accessibility Gameplay",
            ]
        )

    @staticmethod
    def renderLead():
        """Renders the shown pages in sidebar for leaderboard."""
        PageRender.showPages()
        hide_pages(
            [
                "Game Map",
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Stats",
                "Shooting Minigame",
                "Accessibility Gameplay",
            ]
        )

    def renderStats():
        """Renders the shown pages in sidebar for player stats page."""
        PageRender.showPages()
        hide_pages(
            [
                "Game Map",
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Leaderboard",
                "Shooting Minigame",
                "Accessibility Gameplay",
            ]
        )
    
    def renderAccess():
        """Renders the shown pages in sidebar for accessibility page."""
        PageRender.showPages()
        hide_pages(
            [
                "Main Gameplay",
                "You Lost!",
                "You Won!",
                "Trivia",
                "Shooting Minigame",
                "Leaderboard",
                "Stats",
                "Game Map",
                "How to Play",               
            ]
        )
    
    def footer():
        """Win/Lose footer credit text"""
        footer_html = """<div style='text-align: center;'>
            <p>Developed by Victoria Zhang</p>
            <p>Graphics and Audio by Zoë Babbar</p>
            <p>© 2024 Team VOID</p>
        </div>"""
        st.markdown(footer_html, unsafe_allow_html=True)
    
    def credAI():
        """Crediting AI in Trivia if use_ai."""
        footer_html = """<div style='text-align: center;'>
            <p>Trivia questions generated by ChatGPT. </p>
            <p>© 2024 Team VOID</p>
        </div>"""
        st.markdown(footer_html, unsafe_allow_html=True)